#!/bin/bash

# Git Log -S Demo Commands
# This script demonstrates various git log -S searches for the YouTube episode

echo "=== Git Log -S Demo Commands ==="
echo ""
echo "1. Find when Apple Pay was added and removed:"
echo "git log --all --full-history -S 'apple_pay' -- src/config/payment.ts"
echo ""
echo "2. Search for Apple Pay in English translations:"
echo "git log --all --full-history -S 'Apple Pay' -- src/locales/en/payment.json"
echo ""
echo "3. Search for Apple Pay in Arabic translations:"
echo "git log --all --full-history -S 'آبل باي' -- src/locales/ar/payment.json"
echo ""
echo "4. General vs Specific searches:"
echo "git log --all --full-history -S 'Pay' -- src/config/payment.ts"
echo "git log --all --full-history -S 'paypal' -- src/config/payment.ts"
echo "git log --all --full-history -S \"'paypal',\" -- src/config/payment.ts"
echo ""
echo "5. Search for Google Pay:"
echo "git log --all --full-history -S 'google_pay' -- src/config/payment.ts"
echo ""
echo "6. Search for function additions:"
echo "git log --all --full-history -S 'getEnabledPaymentMethods' -- src/services/payment-methods.ts"
echo ""
echo "7. Show the actual changes in a commit:"
echo "git show 28ca1c5884a543cc885a1abde60ac27ff9a6ffe6 -- src/config/payment.ts"
echo ""
echo "8. Verify commit belongs to main branch:"
echo "git merge-base --is-ancestor 28ca1c5884a543cc885a1abde60ac27ff9a6ffe6 HEAD && echo 'YES - in current branch' || echo 'NO - not in current branch'"
echo ""
echo "9. View the git graph:"
echo "git log --oneline --graph --all"
echo ""
echo "=== End of Demo Commands ==="