#!/bin/bash

# Git Log -S Demo Commands
# This script demonstrates various git log -S searches for the YouTube episode

echo "=== Git Log -S Demo Commands ==="
echo ""
echo "=== The Pain Scenario ==="
echo ""
echo "1. Show the painful git history (48+ commits):"
echo "git log --oneline"
echo "# Try scrolling through this manually to find Apple Pay changes!"
echo ""
echo "=== Basic Git Log -S Examples ==="
echo ""
echo "2. Find when Apple Pay was added and removed (instant results):"
echo "git log --all --full-history -S 'apple_pay' -- src/config/payment.ts"
echo ""
echo "3. Search for Apple Pay in English translations:"
echo "git log --all --full-history -S 'Apple Pay' -- src/locales/en/payment.json"
echo ""
echo "4. Search for Apple Pay in Arabic translations:"
echo "git log --all --full-history -S 'آبل باي' -- src/locales/ar/payment.json"
echo ""
echo "5. General vs Specific searches:"
echo "git log --all --full-history -S 'Pay' -- src/config/payment.ts"
echo "git log --all --full-history -S 'paypal' -- src/config/payment.ts"
echo "git log --all --full-history -S \"'paypal',\" -- src/config/payment.ts"
echo ""
echo "6. Search for Google Pay:"
echo "git log --all --full-history -S 'google_pay' -- src/config/payment.ts"
echo ""
echo "7. Search for function additions:"
echo "git log --all --full-history -S 'getEnabledPaymentMethods' -- src/services/payment-methods.ts"
echo ""
echo "8. Show the actual changes in a commit:"
echo "git show 0d838d3 -- src/config/payment.ts"
echo ""
echo "9. Show who removed Apple Pay:"
echo "git log --format='%an' 0d838d3^..0d838d3"
echo ""
echo "=== Deployment Pipeline Investigation ==="
echo ""
echo "10. Check Apple Pay status in PROD:"
echo "git checkout PROD"
echo "git log --full-history -S 'apple_pay' -- src/config/payment.ts"
echo ""
echo "11. Check Apple Pay status in UAT:"
echo "git checkout UAT"
echo "git log --full-history -S 'apple_pay' -- src/config/payment.ts"
echo ""
echo "12. Check Apple Pay status in QC:"
echo "git checkout QC"
echo "git log --full-history -S 'apple_pay' -- src/config/payment.ts"
echo ""
echo "13. Verify deployment of Apple Pay removal:"
echo "git checkout QC"
echo "git merge-base --is-ancestor 0d838d3 HEAD && echo 'YES - deployed to QC' || echo 'NO - not in QC'"
echo ""
echo "git checkout UAT"
echo "git merge-base --is-ancestor 0d838d3 HEAD && echo 'YES - deployed to UAT' || echo 'NO - not in UAT'"
echo ""
echo "git checkout PROD"
echo "git merge-base --is-ancestor 0d838d3 HEAD && echo 'YES - deployed to PROD' || echo 'NO - not in PROD'"
echo ""
echo "14. Compare environments:"
echo "git diff UAT QC -- src/config/payment.ts"
echo ""
echo "15. View deployment timeline:"
echo "git log --oneline --graph --all --decorate"
echo ""
echo "16. View release tags:"
echo "git tag --list"
echo ""
echo "=== Return to main branch ==="
echo "git checkout main"
echo ""
echo "=== End of Demo Commands ==="